### ISSUE TITLE
filterTermEncrypted still needs work

### ISSUE THREAD

**Issue by MaximilianKrambach** [MaximilianKrambach/enigmail_fork#5]
not yet adressed:
"You try to determine the content type and the protocol in a very naive way (as you write yourself). A much better way would be to parse the message using getMimeTree() in mime.jsm and then return the correct result. See for example enumerateMimeParts() in enigmailMessengerOverlay.js for how to use the resulting tree structure."

**Comment by MaximilianKrambach** [comment]
Part of #1

**Comment by AndreHeinecke** [comment]
Done as a first step because the functionality is independent of our other patches and this reduces the amount of changes we need to get upstream.
